sonar.projectKey=SQLutions-FATEC_API-5-Semestre-Backend
sonar.organization=sqlutions-fatec

sonar.projectName=API-5-Semestre-Backend

sonar.sources=.

sonar.exclusions=**/migrations/**, venv/**, **/*.html, manage.py
sonar.coverage.exclusions=django/api/settings.py, django/api/asgi.py, django/api/wsgi.py, django/api/admin.py, django/api/models.py, django/api/urls.py, django/api/management/commands/seed_db.py

sonar.tests=django/api/
sonar.test.inclusions=django/api/tests.py

sonar.python.coverage.reportPaths=django/coverage.xml
