sonar.projectKey=SQLutions-FATEC_API-5-Semestre-Backend
sonar.organization=sqlutions-fatec

sonar.projectName=API-5-Semestre-Backend

sonar.sources=django

sonar.exclusions=**/migrations/**, venv/**, **/*.html, django/manage.py, django/api/api-endpoints.md, django/etl/etl-process.md, **/data/**, **/__pycache__/**, **/*.pyc
sonar.coverage.exclusions=django/api/settings.py, django/api/asgi.py, django/api/wsgi.py, django/api/admin.py, django/api/models.py, django/api/urls.py, django/api/management/commands/seed_db.py, django/etl/admin.py, django/etl/models.py, django/etl/apps.py, django/etl/management/commands/run_etl.py

sonar.test.inclusions=django/api/tests.py,django/etl/tests/*.py
sonar.python.coverage.reportPaths=django/coverage.xml
