sonar.projectKey=SQLutions-FATEC_API-5-Semestre-Backend
sonar.organization=sqlutions-fatec

sonar.projectName=API-5-Semestre-Backend

sonar.sources=.

sonar.exclusions=**/migrations/**, venv/**, **/*.html, manage.py

sonar.python.coverage.reportPaths=django/coverage.xml
