# Generated by Django 6.0.3 on 2026-03-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fornecedor', models.CharField()),
                ('razao_social', models.CharField()),
                ('cidade', models.CharField()),
                ('estado', models.CharField()),
                ('categoria', models.CharField()),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DimMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField()),
                ('descricao', models.CharField()),
                ('categoria', models.CharField()),
                ('fabricante', models.CharField()),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DimPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_programa', models.CharField()),
                ('nome_programa', models.CharField()),
                ('gerente_programa', models.CharField()),
                ('gerente_tecnico', models.CharField()),
                ('status', models.CharField()),
                ('data_fim_prevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_data_fim_prevista', to='api.dimdata')),
                ('data_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_data_inicio', to='api.dimdata')),
            ],
        ),
        migrations.CreateModel(
            name='DimProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_projeto', models.CharField()),
                ('nome_projeto', models.CharField()),
                ('responsavel', models.CharField()),
                ('custo_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField()),
                ('data_fim_prevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_data_fim_prevista', to='api.dimdata')),
                ('data_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_data_inicio', to='api.dimdata')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimprograma')),
            ],
        ),
        migrations.CreateModel(
            name='DimSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitacao', models.CharField(max_length=6)),
                ('quantidade', models.IntegerField()),
                ('prioridade', models.CharField()),
                ('status', models.CharField()),
                ('data_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimdata')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimmaterial')),
                ('projeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimprojeto')),
            ],
        ),
        migrations.CreateModel(
            name='DimTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tarefa', models.CharField(max_length=6)),
                ('titulo', models.CharField()),
                ('responsavel', models.CharField()),
                ('estimativa', models.IntegerField()),
                ('status', models.CharField()),
                ('data_fim_prevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_data_fim_prevista', to='api.dimdata')),
                ('data_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_data_inicio', to='api.dimdata')),
                ('projeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimprojeto')),
            ],
        ),
        migrations.CreateModel(
            name='FatoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(unique=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField()),
                ('data_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_data_pedido', to='api.dimdata')),
                ('data_previsao_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_data_previsao_entrega', to='api.dimdata')),
                ('fornecedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimfornecedor')),
                ('solicitacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimsolicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='FatoEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_empenhada', models.IntegerField()),
                ('data_empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimdata')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimmaterial')),
                ('projeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimprojeto')),
            ],
        ),
        migrations.CreateModel(
            name='FatoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField()),
                ('horas_trabalhadas', models.FloatField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimdata')),
                ('tarefa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimtarefa')),
            ],
        ),
    ]
