# Generated by Django 6.0.3 on 2026-03-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimprojeto',
            old_name='programa_id',
            new_name='programa',
        ),
        migrations.RenameField(
            model_name='dimsolicitacao',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='dimsolicitacao',
            old_name='projeto_id',
            new_name='projeto',
        ),
        migrations.RenameField(
            model_name='dimtarefa',
            old_name='projeto_id',
            new_name='projeto',
        ),
        migrations.RenameField(
            model_name='fatocompra',
            old_name='fornecedor_id',
            new_name='fornecedor',
        ),
        migrations.RenameField(
            model_name='fatocompra',
            old_name='solicitacao_id',
            new_name='solicitacao',
        ),
        migrations.RenameField(
            model_name='fatoempenho',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='fatoempenho',
            old_name='projeto_id',
            new_name='projeto',
        ),
        migrations.RenameField(
            model_name='fatotarefa',
            old_name='tarefa_id',
            new_name='tarefa',
        ),
    ]
