# Generated by Django 5.2.12 on 2026-03-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_programa_id_dimprojeto_programa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimprojeto',
            name='is_atrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dimprojeto',
            name='lead_time_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dimtarefa',
            name='is_atrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dimtarefa',
            name='lead_time_dias',
            field=models.IntegerField(default=0),
        ),
    ]
