# Generated by Django 5.2.12 on 2026-04-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dimfornecedor_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimfornecedor',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dimprograma',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dimprojeto',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dimsolicitacao',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dimtarefa',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fatocompra',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
