# Generated by Django 5.2.12 on 2026-04-28 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dimprojeto_is_atrasado_dimprojeto_lead_time_dias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_localizacao', models.CharField()),
                ('localizacao', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='FatoEstoqueSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_disponivel', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_ultima_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimdata')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimlocalizacao')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimmaterial')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimprojeto')),
            ],
        ),
    ]
