global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['django-app:8000']

  - job_name: 'mysql-metrics'
    static_configs:
      - targets: 
          - 'mysql-exporter:9104'
          - 'mysql-exporter-prod:9104'