# Configurações padrões para quando rodar o comando locust puro
locustfile = locustfile.py
host = http://localhost:8000

# Parâmetros recomendados para o modo headless (se for usado)
users = 50
spawn-rate = 5
run-time = 10m