name: Deploy Automático 

on:
  push:
    branches:
      - develop-4 

jobs:
  # -------------------------------------------------------------
  # DEPLOY: AWS ECS Fargate
  # -------------------------------------------------------------
  deploy:
    name: Deploy para AWS ECS Fargate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, e Push das Imagens para o ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # 1. Backend Django 
          docker build -t $ECR_REGISTRY/api-backend:latest -f deploy/backend/Dockerfile ./django
          docker push $ECR_REGISTRY/api-backend:latest

          # 2. Nginx
          docker build -t $ECR_REGISTRY/api-nginx:latest deploy/nginx
          docker push $ECR_REGISTRY/api-nginx:latest

          # 3. Prometheus
          docker build -t $ECR_REGISTRY/api-prometheus:latest deploy/monitoring/prometheus
          docker push $ECR_REGISTRY/api-prometheus:latest

          # 4. Grafana
          docker build -t $ECR_REGISTRY/api-grafana:latest deploy/monitoring/grafana
          docker push $ECR_REGISTRY/api-grafana:latest

          # 5. MySQL Exporter
          docker build -t $ECR_REGISTRY/api-mysql-exporter:latest deploy/monitoring/mysql-exporter
          docker push $ECR_REGISTRY/api-mysql-exporter:latest

      - name: Atualizar o Serviço no ECS
        run: |
          # Este comando avisa a AWS para baixar as imagens novas e reiniciar os containers sem downtime
          aws ecs update-service \
            --cluster meu-cluster-api \
            --service meu-servico-api \
            --force-new-deployment